apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-frontend
  namespace: production
  labels:
    app: enterprise-frontend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: enterprise-frontend

  template:
    metadata:
      labels:
        app: enterprise-frontend

    spec:
      serviceAccountName: enterprise-frontend-sa
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: enterprise-frontend
          image: ghcr.io/cassianomeneghetti/enterprise-platform-frontend:e158882e5af144049e053ca9576313b9d3650c97
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - SETGID
                - SETUID

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"

          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /run

      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
