apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: production
  labels:
    app: redis-exporter

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis-exporter

  template:
    metadata:
      labels:
        app: redis-exporter

    spec:
      serviceAccountName: redis-exporter
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.62.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 59000
            runAsGroup: 59000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          args:
            - --redis.addr=redis://redis:6379

          ports:
            - name: metrics
              containerPort: 9121

          readinessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "96Mi"
