apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-api
  namespace: production
  labels:
    app: enterprise-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: enterprise-api

  template:
    metadata:
      labels:
        app: enterprise-api

    spec:
      serviceAccountName: enterprise-api-sa
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: enterprise-api
          image: ghcr.io/cassianomeneghetti/enterprise-platform-api:e97fdd7fa4cba1a3eb6fe24b3a0e3c87cb8133f7
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
