apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-exporter
  namespace: production
  labels:
    app: postgresql-exporter

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgresql-exporter

  template:
    metadata:
      labels:
        app: postgresql-exporter

    spec:
      serviceAccountName: postgresql-exporter
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: postgresql-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - name: metrics
              containerPort: 9187

          env:
            - name: DATA_SOURCE_URI
              value: "postgresql:5432/enterprise?sslmode=disable"
            - name: DATA_SOURCE_USER
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 30
            periodSeconds: 20

          resources:
            requests:
              cpu: "25m"
              memory: "48Mi"
            limits:
              cpu: "150m"
              memory: "128Mi"
