apiVersion: v1
kind: Service
metadata:
  name: postgresql-exporter
  namespace: production
  labels:
    app: postgresql-exporter

spec:
  type: ClusterIP

  selector:
    app: postgresql-exporter

  ports:
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
